services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: "AQUI_VA_TU_API_KEY"
    container_name: spacex_dashboard
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=AQUI_VA_TU_API_KEY
